export { Modal } from "./modal";
export { Option } from "./option";
export { GameArea } from "./gameArea";
export { Header } from "./header";
export { Score } from "./score";
export { Logo } from "./logo";
export { Card } from "./card";
export { Result } from "./result";
export { Shadow } from "./shadow";
